config/routes.rb
DeviseRspecCucumber::Application.routes.draw do
  authenticated :user do
    root to: "users#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "home#index", as: :unauthenticated_root
    devise_for :users
    resources :users
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name
  validates_uniqueness_of :name, :email, case_sensitive: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

  devise_parameter_sanitizer.for(:sign_up) << :name

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Devise-rspec-cucumber", unauthenticated_root_path, class: "brand"
%ul.nav
  - if user_signed_in?
    %li
      = link_to "Logout", destroy_user_session_path, method: "delete"
  - else
    %li
      = link_to "Login", new_user_session_path
  - if user_signed_in?
    %li
      = link_to "Edit", edit_user_registration_path
  - else
    %li
      = link_to "Sing up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Devise-Rspec-Cucumber"
    %meta{:content => content_for?(:description) ? yield(:description) : "Devise-Rspec-Cucumber", :name => "description"}/
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body{:class => "#{controller_name} #{action_name}"}
    #container.container
      %header
        = render 'layouts/navigation'
        = render 'layouts/messages'
      #main{:role => "main"}
        = yield
      %footer
    / ! end of #container

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p User: #{@user.name}
%p Email: #{@user.email if @user.email}